### ISSUE TITLE
Building the initial structure for the project, including: - Creating directories (notebooks, scripts, data, models). - . - Initializing requirements.txt ...

### ISSUE THREAD

**Issue by Linchenpal** [yukaberry/detect_ai_content#10]

**Comment by Linchenpal** [comment]
Steps: ( terminal)
	1.	Navigate to the Project Directory Locally: git clone git@github.com:yukaberry/detect_ai_content.git
	2.     Navigate into the project directory: cd detect_ai_content
	3.     Create the Directory Structure Locally: mkdir notebooks scripts data model ....
         4.    Add, Commit, and Push the Structure to the Repository

**Comment by leverdewagon** [comment]
@Linchenpal  @yukaberry , maybe this issue can be "fixed" by the open PR : https://github.com/yukaberry/detect_ai_content/pulls

**Comment by Linchenpal** [comment]
@leverdewagon yep. we ait for approve of Yuka and we merge...
