### ISSUE TITLE
Identify datasets for MVP

### ISSUE THREAD

**Issue by aban371818** [yukaberry/detect_ai_content#2]

**Comment by leverdewagon** [comment]
For AI detection in Texts : 

- https://www.kaggle.com/datasets/thedrcat/daigt-v2-train-dataset
- https://www.kaggle.com/competitions/llm-detect-ai-generated-text
-

**Comment by yukaberry** [comment]
https://www.kaggle.com/competitions/llm-detect-ai-generated-text/leaderboard
https://www.kaggle.com/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/data

**Comment by yukaberry** [comment]
text (from Ab) : https://huggingface.co/datasets/artem9k/ai-text-detection-pile
text (from TAs! ) : https://www.kaggle.com/datasets/starblasters8/human-vs-llm-text-corpus/data?select=data.csv

text (from TAs) : https://www.kaggle.com/datasets/shanegerami/ai-vs-human-text/data
text (from TAs): https://www.kaggle.com/datasets/jdragonxherrera/augmented-data-for-llm-detect-ai-generated-text
text (from TAs): https://www.kaggle.com/datasets/thedrcat/daigt-v2-train-dataset
