### ISSUE TITLE
Reduce computation time

### ISSUE THREAD

**Issue by yukaberry** [yukaberry/detect_ai_content#61]
@leverdeterre, would be great if you could advise here what you usually do to reduce computation time. 

Ben TA advice 
-  convert txt for smaller size (font size, bit size 64 to 32 or 8. ) 

Try out 
-  use different model : check out hugging face model for ai vs human and try it out 
-  use hugging face transformer  (specialized for AI vs human) 
-  use hugging face tokeniser (specialized for AI vs human) 

Test 
- try to see if first few api calls are slower. (lazy loading. after a while, it will sort of stop) 
- test character length. find the best length 

Target (manager Ben) 
- 0.2-0.3 computing time as a target

**Comment by leverdewagon** [comment]
👍

**Comment by yukaberry** [comment]
Tip from Ben manager 

* divide code into small parts, try to optimize each part step by step
-  loop over too many times? 
- change data type if possible  df --> numpy --> tensor  

* compute and print time to find where it is slow.  

* throw code into chatgpt and ask 'optimize this code'

**Comment by leverdewagon** [comment]
Done !
